spring:
    kafka:
        bootstrap-servers: 121.41.47.113:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            group-id: demo
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            auto-offset-reset: earliest
        template:
            default-topic: demo 
    cache:
        type: redis
        redis:
            time-to-live: 1m
            key-prefix: "demo::"
    application:
        name: demo
    data:
        redis:
            host: 121.41.47.113
            port: 6379
            database: 0
            password: 5KNXvtUSWsmsXKw4ySWb
        mongodb:
            database: test
            uri: mongodb://mongo:yrP5dAbcTBaCAxfDz56G@121.41.47.113:27017/test?authSource=admin
server:
    port: 18080
